# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDHBawmRPW-MkjJ--m80gt1ayABmPCa8
"""

import tensorflow as tf
tf.compat.v1.disable_eager_execution()
#create a computational graph
node1=tf.constant(3.0, tf.float32)
node2=tf.constant(4.0)
#inorder to get the values from nodes we have to evaluate the nodes
#so we run the computational graph inside a session
sess = tf.compat.v1.Session()
print(sess.run([node1,node2]))