# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OdC0xqFkFsXIZCRO0zw_eNXJR0FSBHV6
"""

#placeholder is used for input data. here, we wren't using any constant nodes
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


a=tf.placeholder(tf.float32) #it'll be a float number of 32 
b=tf.placeholder(tf.float32)

add=a+b
sess=tf.compat.v1.Session()
#ading 1and 2 , 3 and 4 
print(sess.run(add,{a:[1,3],b:[2,4]})) #add is the var we are performimg, and we are feeding a dict. as values a=a list of int values between 1-3