# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GBk4QkMK06JYk0gMidUP9N0nFw1xpVSQ
"""

import tensorflow as tf
tf.compat.v1.disable_eager_execution()
#defining 3 constant nodes
a=tf.constant(5)
b=tf.constant(2)
c=tf.constant(3)

#performimg operations
d=tf.multiply(a,b) #multiplying a and b
e=tf.add(c,b) #adding c and b

f=tf.subtract(d,e)
sess= tf.compat.v1.Session()

out=sess.run(f)
print(out)